// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgG2u1bXjCEmeebFtmByUGGR_zD4t1p0',
    appId: '1:928329827100:web:eca4dd533af0322b01f0d9',
    messagingSenderId: '928329827100',
    projectId: 'crud-81d2f',
    authDomain: 'crud-81d2f.firebaseapp.com',
    storageBucket: 'crud-81d2f.appspot.com',
    measurementId: 'G-B4WL3NB7VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5RXi9kWGZcGRGmAEZmGWI8M33gYac7BE',
    appId: '1:928329827100:android:ffe943fa4cfcb4d601f0d9',
    messagingSenderId: '928329827100',
    projectId: 'crud-81d2f',
    storageBucket: 'crud-81d2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmOYF-1IAdBNKYc-wn0-ZEByzTyk4BvSQ',
    appId: '1:928329827100:ios:d601a0a7e866494101f0d9',
    messagingSenderId: '928329827100',
    projectId: 'crud-81d2f',
    storageBucket: 'crud-81d2f.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmOYF-1IAdBNKYc-wn0-ZEByzTyk4BvSQ',
    appId: '1:928329827100:ios:d8e1fe66dbbd4efc01f0d9',
    messagingSenderId: '928329827100',
    projectId: 'crud-81d2f',
    storageBucket: 'crud-81d2f.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
